version: "3.9"

services:
  mongo_db:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CLUSTER_NAME: ${DB_CLUSTER_NAME}
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}