name: 01.Node.js Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies with npm
        run: npm install
        continue-on-error: false
        id: install-dependencies

      - name: Install Railway CLI
        run: npm i -g @railway/cli
        continue-on-error: false
        id: install-railway-cli
        
      - name: Deploy to Railway
        run: railway up --service node-dockerize-cicd
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        continue-on-error: false
        id: deploy-to-railway

      # Success/Failure message after key steps
      - name: Check Success/Failure Messages
        if: always()
        run: |
          if [ ${{ steps.install-dependencies.outcome }} == 'success' ]; then
            echo "✅ Dependencies installed successfully!"
          else
            echo "❌ Failed to install dependencies!"
            exit 1
          fi

          if [ ${{ steps.install-railway-cli.outcome }} == 'success' ]; then
            echo "✅ Railway CLI installed successfully!"
          else
            echo "❌ Railway CLI installation failed!"
            exit 1
          fi

          if [ ${{ steps.deploy-to-railway.outcome }} == 'success' ]; then
            echo "✅ Successfully deployed to Railway!"
          else
            echo "❌ Deployment to Railway failed!"
            exit 1
          fi
        continue-on-error: false