name: 01.Node.js Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out the code from the repository

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        id: login-docker-hub
        continue-on-error: false

      - name: Build Docker Image
        run: docker build -t zyffyz/ci-cd  .
        id: build-image
        continue-on-error: false

      - name: Publish Image to docker hub
        run: docker push zyffyz/ci-cd:latest
        id: publish-image
        continue-on-error: false

      # Success/Failure message after key steps
      - name: Check Success/Failure Messages for build
        run: |

          if [ "${{ steps.login-docker-hub.outcome }}" = "success" ]; then
            echo "✅ Successfully logged in to Docker Hub!"
          else
            echo "❌ Failed to log in to Docker Hub!"
            exit 1
          fi

          if [ "${{ steps.build-image.outcome }}" = "success" ]; then
            echo "✅ Successfully built Docker Image!"
          else
            echo "❌ Failed to build Docker Image!"
            exit 1
          fi

          if [ "${{ steps.publish-image.outcome }}" = "success" ]; then
            echo "✅ Successfully published Docker Image!"
          else
            echo "❌ Failed to publish Docker Image!"
            exit 1
          fi
        continue-on-error: false

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull zyffyz/ci-cd:latest 
        id: pull-image
        continue-on-error: false

      - name: Delete old container
        run: docker rm -f nodejs-app-container
        id: delete-container
        continue-on-error: false

      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name nodejs-app-container -e DB_HOST='${{ secrets.DB_HOST }}' -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' -e DB_CLUSTER_NAME='${{ secrets.DB_CLUSTER_NAME }}'  zyffyz/ci-cd
        id: run-container
        continue-on-error: false

      # Success/Failure message after key steps
      - name: Check Success/Failure Messages for Deploy
        run: |

          if [ "${{ steps.pull-image.outcome }}" = "success" ]; then
            echo "✅ Successfully pulled Docker Image!"
          else
            echo "❌ Failed to pull Docker Image!"
            exit 1
          fi

          if [ "${{ steps.delete-container.outcome }}" = "success" ]; then
            echo "✅ Successfully deleted old container!"
          else
            echo "❌ Failed to delete old container!"
            exit 1
          fi

          if [ "${{ steps.run-container.outcome }}" = "success" ]; then
            echo "✅ Successfully deployed container!"
          else
            echo "❌ Failed to deploy container!"
            exit 1
          fi
        continue-on-error: false